language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
install:
  - pip install -e .
  - pip install requests
before_script:
  - docker-compose -f tests/config/docker-compose.yml up -d
  - sleep 15
script: py.test -v
after_script:
  - docker-compose down
